Use the following code for the questions below:


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


1. How many negative numbers are there?

In [5]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [6]:
negative_count = np.sum(a < 0)
negative_count

4

2. How many positive numbers are there?



In [7]:
positive_number = np.sum(a > 0)
positive_number

5

3. How many even positive numbers are there?

In [9]:
even_positive_number = np.sum((a > 0) & (a % 2 == 0))
#(a % 2 == 0) creates a Boolean array that checks if each element of a is both positive and even
even_positive_number

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [10]:
a_shifted = a + 3
positive_number = np.sum(a_shifted > 0)
positive_number

10

5. If you squared each number, what would the new mean and standard deviation be?

In [27]:
a_squared = a ** 2
a_squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [29]:
Updated_mean = np.mean(a_squared)
Updated_mean

74.0

In [31]:
updated_stddev = np.std(a_squared)
updated_stddev

144.0243035046516

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [34]:
centered_data = a - np.mean(a)
centered_data

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z= x−μ/σ

#The code (a - np.mean(a)) / np.std(a) subtracts the mean of a from each element of a and then divides the result by the standard deviation of a, resulting in an array of z-scores.



In [35]:
a - np.mean(a)

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [36]:
np.std(a)

8.06225774829855

In [38]:
z_score = a-np.mean(a)/np.std(a)
z_score


array([ 3.6278958,  9.6278958, 11.6278958, 22.6278958, -2.3721042,
       -1.3721042, -0.3721042, -0.3721042, -0.3721042, -6.3721042,
        2.6278958, -7.3721042])