Use the following code for the questions below:


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


1. How many negative numbers are there?

In [123]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [6]:
negative_count = np.sum(a < 0)
negative_count

4

2. How many positive numbers are there?



In [124]:
np.sum(a > 0)


5

3. How many even positive numbers are there?

In [9]:
even_positive_number = np.sum((a > 0) & (a % 2 == 0))
#(a % 2 == 0) creates a Boolean array that checks if each element of a is both positive and even
even_positive_number

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [10]:
a_shifted = a + 3
positive_number = np.sum(a_shifted > 0)
positive_number

10

5. If you squared each number, what would the new mean and standard deviation be?

In [126]:
a_squared = a ** 2
a_squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [29]:
Updated_mean = np.mean(a_squared)
Updated_mean

74.0

In [31]:
updated_stddev = np.std(a_squared)
updated_stddev

144.0243035046516

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [34]:
centered_data = a - np.mean(a)
centered_data

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z= x−μ/σ

#The code (a - np.mean(a)) / np.std(a) subtracts the mean of a from each element of a and then divides the result by the standard deviation of a, resulting in an array of z-scores.



In [35]:
a - np.mean(a)

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [36]:
np.std(a)

8.06225774829855

In [38]:
z_score = a-np.mean(a)/np.std(a)
z_score


array([ 3.6278958,  9.6278958, 11.6278958, 22.6278958, -2.3721042,
       -1.3721042, -0.3721042, -0.3721042, -0.3721042, -6.3721042,
        2.6278958, -7.3721042])

Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [1]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
sum_of_a = sum(a)
sum_of_a

55

#Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [4]:
min_of_a = min(a)
min_of_a

1

#Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [5]:
max_of_a = max(a)
max_of_a

10

#Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [7]:
mean_of_a = np.mean(a)
mean_of_a

5.5

#Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [8]:
product_of_a = np.prod(a)
product_of_a

3628800

#Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [20]:
squares_of_a = [num ** 2 for num in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [25]:
odds_in_a = [num for num in a if num % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

#Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [26]:
evens_in_a = [num for num in a if num % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

#What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

b = [
    [3, 4, 5],
    [6, 7, 8]
]


In [31]:
import numpy as np
b = [
    [3, 4, 5],
    [6, 7, 8]
]

#Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [ ]:
# Convert b to a NumPy array

In [33]:
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [36]:
import numpy as np

b = np.array(b) 
sum_of_b = np.sum(b)  # Calculate the sum of all elements in b
sum_of_b

33

Exercise 2 - refactor the following to use numpy. 

min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [47]:
min_of_b = np.min(b[:2])
min_of_b

3

In [44]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])



In [128]:
print(max_of_b)

8


Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [127]:
print(mean_of_b)

5.5


Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [49]:
product_of_b = np.prod(b)
product_of_b

20160

Exercise 6 - refactor the following to use numpy to find the list of squares 

squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


In [131]:
squares_of_b = np.square(b).tolist()
squares_of_b

[[9, 16, 25], [36, 49, 64]]

In [130]:
squares_of_b

[[9, 16, 25], [36, 49, 64]]

Exercise 7 - refactor using numpy to determine the odds_in_b

odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


In [63]:
odds_in_b = np.extract(b % 2 != 0, b).tolist()
odds_in_b

[3, 5, 7]

#Exercise 8 - refactor the following to use numpy to filter only the even numbers

evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [64]:
evens_in_b = np.extract( b % 2 == 0, b).tolist()
evens_in_b

[4, 6, 8]

Exercise 9 - print out the shape of the array b.

In [66]:
b = np.array(b) 
b.shape

(2, 3)

Exercise 10 - transpose the array b.

In [67]:
b_transpose = np.transpose(b)
b_transpose

array([[3, 6],
       [4, 7],
       [5, 8]])

 Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [71]:
b_reshaped = b.reshape(1, 6)
b_reshaped

array([[3, 4, 5, 6, 7, 8]])

#Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [73]:
b_reshaped = b.reshape(6,1).tolist()
b_reshaped

[[3], [4], [5], [6], [7], [8]]

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [75]:
import numpy as np
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

#Exercise 1 - Find the min, max, sum, and product of c.


In [78]:
min_of_c = np.min(c)
min_of_c

1

In [79]:
max_of_c = np.max(c)
max_of_c

9

In [80]:
sum_of_c = np.sum(c)
sum_of_c

45

In [81]:
product_of_c = np.prod(c)
product_of_c

362880

 Exercise 2 - Determine the standard deviation of c.

In [82]:
std_of_c = np.std(c)
std_of_c

2.581988897471611

Exercise 3 - Determine the variance of c.

In [83]:
var_of_c = np.var(c)
var_of_c

6.666666666666667

Exercise 4 - Print out the shape of the array c

In [84]:
shape_of_c = np.shape(c)
shape_of_c

(3, 3)

Exercise 5 - Transpose c and print out transposed result.


In [86]:
transpose_of_c = np.transpose(c)
transpose_of_c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Exercise 6 - Get the dot product of the array c with c. 

In [88]:
dot_product = np.dot(c,c)
dot_product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [93]:
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [95]:
result_c = np.sum(c * np.transpose(c))

result_c

261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [100]:
#np.multiply(c, np.transpose(c)) performs element-wise 
#multiplication between c and its transpose
product = np.multiply(c, np.transpose(c))
result = np.prod(product)
result

131681894400

In [133]:
import numpy as np

d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

Exercise 1 - Find the sine of all the numbers in d


In [103]:
sine_d = np.sin(d)
sine_d

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d

In [104]:
cosine_d = np.cos(d)
cosine_d

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d


In [108]:
tangent_d = np.sin(d) / np.cos(d)
tangent_d

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#Exercise 4 - Find all the negative numbers in d


In [113]:
negative_d = np.negative([1. -1])
negative_d

array([-0.])

In [116]:
negative_numbers = np.array(d)[np.array(d) < 0]
negative_numbers

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d


In [117]:
positive_numbers = np.array(d)[np.array(d)>0]
positive_numbers

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d.


In [118]:
unique_numbers = np.unique(d)
unique_numbers

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.


In [119]:
unique_numbers = np.unique(d)
num_unique_numbers = unique_numbers.size
num_unique_numbers


11

Exercise 8 - Print out the shape of d.


In [135]:
d_array = np.array(d)  
print(d_array.shape)

(3, 6)


#Exercise 9 - Transpose and then print out the shape of d.


In [139]:
np.shape(np.transpose(d))


(6, 3)

#Exercise 10 - Reshape d into an array of 9 x 2


In [144]:
np.reshape(d,(9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])